server:
  port: 8803
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: serviceBook
          uri: http://localhost:8801
          predicates:
            - Path=/book/**
        - id: serviceAuthor
          uri: http://localhost:8802
          predicates:
            - Path=/author/**
  cache:
    cache-names:
    - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

    