server:
  port: 8803
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: serviceBook
          uri: http://localhost:8801
          predicates:
            - Path=/book/**
          filters:
          - CircuitBreaker=serviceBook
          - name: Retry
            args:
              retries: 5
              statuses: BAD_GATEWAY
              methods: GET
              backoff:
                firstBackoff: 10ms
                maxBackoff: 50ms
                factor: 2
                basedOnPreviousValue: false
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
        - id: serviceAuthor
          uri: http://localhost:8802
          predicates:
            - Path=/author/**
          filters:
          - CircuitBreaker=serviceAuthor
          - name: Retry
            args:
              retries: 5
              statuses: BAD_GATEWAY
              methods: GET
              backoff:
                firstBackoff: 10ms
                maxBackoff: 50ms
                factor: 2
                basedOnPreviousValue: false
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20

  cache:
    cache-names:
    - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      serviceBook:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED 
      serviceAuthor:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED   
  retry:
    retry-aspect-order: 2
    instances:
      serviceBook:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
         - org.springframework.web.client.RestClientException
      serviceAuthor:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
         - org.springframework.web.client.RestClientException 

  
     

